# Generated by Django 2.1 on 2018-08-23 06:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTPkey',
            field=models.CharField(default=datetime.datetime(2018, 8, 23, 6, 38, 42, 20746, tzinfo=utc), max_length=4000),
            preserve_default=False,
        ),
    ]
