# Generated by Django 2.1 on 2018-08-23 09:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_otpkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='OTPQr',
            field=models.ImageField(default=datetime.datetime(2018, 8, 23, 9, 21, 36, 240583, tzinfo=utc), upload_to='images/scans'),
            preserve_default=False,
        ),
    ]
