# Generated by Django 2.1 on 2018-08-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_otpqr'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_scanned',
            field=models.BooleanField(default=False),
        ),
    ]
